micronaut:
  application:
    name: lojaDeLivros
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.0.0.1:9042"
      session-keyspace: livro
      load-balancing-policy:
        local-datacenter: datacenter1

## Nats
nats:
  addresses: ${nats_host:localhost}
  username: ${nats_username:guest}
  password: ${nats_password:guest}

#  ## Swagger
#  router:
#    versioning:
#      enabled: true
#      default-version: 1
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**
#      redoc:
#        paths: classpath:META-INF/swagger/views/redoc
#        mapping: /redoc/**
#      rapidoc:
#        paths: classpath:META-INF/swagger/views/rapidoc
#        mapping: /rapidoc/**
#      swagger-ui:
#        paths: classpath:META-INF/swagger/views/swagger-ui
#        mapping: /swagger-ui/**
#    endpoints:
#      all:
#        enabled: true
#        sensitive: false
#      health:
#        enabled: true
#      beans:
#        enabled: true
#      info:
#        enabled: true
#      routes:
#        enabled: true
